---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
```
## read in csv data
```{r}
data_rg <- read.csv("data/N1.csv")
```

### prepare the data for FFT
```{r}
cycle = 1000
data1 <- data_rg %>%
  filter(cycles == cycle) %>%
  mutate(time_cyc = (X-X[1]) * 0.005)
```

### run FFT with different windows
T - total sampling time
N - total sample taken
sr - sampling rate
si - T/N 
f0 - 1/T, frequency resolution, or harmonic 
### proof of concept
```{r}
acq.freq <- 200       # data acquisition frequency (Hz)
sig1.freq <- 5       # frequency of 1st signal component (Hz)
sig2.freq <- 13      # frequency of 2nd signal component (Hz)
time <- 5            # measuring time interval (s)

# vector of sampling time-points (s)
smpl.int <- (1:(time*acq.freq))/acq.freq  

# data vector containing two frequencies (2nd frequ with phase shift)
data <- sin(sig1.freq*smpl.int*2*pi)+sin(sig2.freq*smpl.int*2*pi+pi/2)

plot(smpl.int, data,type="l")

# calculate fft of data
test <- fft(data)

# extract magnitudes and phases
magn <- Mod(test) # sqrt(Re(test)*Re(test)+Im(test)*Im(test))
phase <- Arg(test) # atan(Im(test)/Re(test))

# select only first half of vectors
magn.1 <- magn[2:(length(magn)/2)]
#phase.1 <- Arg(test)[1:(length(test)/2)]

# generate x-axis with frequencies
x.axis <- 1:length(magn.1)/time

# plot magnitudes against frequencies
plot(x=x.axis,y=magn.1,type="l",
     xlim=c(0, 15))

# write data into csv file
x <- seq(1, length(data))

data_fft <- data.frame(X=x, cycles=1000, position=data, time=data,
                       friction=data, load=data, trigger=data)

write.csv(data_fft, file='data/N2.csv')
```

### analysis for actual data
```{r}

cycle = 1000

data1 <- data_rg %>%
  filter(cycles == cycle) %>%
  mutate(time_cyc = (X-X[1]) * 0.005)

x = data1$time_cyc
y = data1$load


acq.freq <- 200      # data acquisition frequency (Hz)

smpl.int <- x

data <- y

plot(smpl.int, data,type='l')

# calculate fft of data
test <- fft(data)

# extract magnitudes and phases
magn <- Mod(test) # sqrt(Re(test)*Re(test)+Im(test)*Im(test))
phase <- Arg(test) # atan(Im(test)/Re(test))

# select only first half of vectors
magn.1 <- magn[1:(length(magn)/2)]
#phase.1 <- Arg(test)[1:(length(test)/2)]

# generate x-axis with frequencies
x.axis <- 1:length(magn.1)/time

# plot magnitudes against frequencies
plot(x=x.axis,y=magn.1,type="l", xlim=c(0, 1))

write.csv(data1, file='data/N3.csv')
```

